### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bfontaine** [paulmars/huffshell#18]
Hi,
I’d like to make a pull-request for huffshell but I don’t know what is its license. Technically if it doesn’t have any license it’s proprietary code. I’d suggest the MIT license.

It’d be nice if you could add a `LICENSE` file in the repo.

**Comment by paulmars** [comment]
Submit a pull request with MIT license?

Paul McKellar


On December 22, 2015 at 4:32:43 PM, Baptiste Fontaine (notifications@github.com) wrote:

Hi,
I’d like to make a pull-request for huffshell but I don’t know what is its license. Technically if it doesn’t have any license it’s proprietary code. I’d suggest the MIT license.
